export default {
  titleH1: 'Calibri Light',
  subTitleH1: 'Calibri Light',
  button: 'Calibri Light',
  subTitleH2: 'Calibri Light',
  titleH3: 'Calibri',
  subTitleH3: 'Calibri Light',

  icons: {
    antdesign: 'antdesin',
    entypo: 'entypo',
    evilicon: 'evilicon',
    feather: 'feather',
    fontAwesome: 'fontawesome',
    fontAwesome5: 'font-awesome-5',
    fontisto: 'fontisto',
    foundation: 'foundation',
    ionicon: 'ionicon',
    material: 'material',
    materialCommunity: 'material-communit',
    octicon: 'octicon',
    simpleLineIcon: 'simple-line-icon',
    zocial: 'zocial',
  },

  //subTitle: 'Calibri',
  text: 'Calibri Light',
  value: 'Calibri Light',
  code: 'Calibri Light',
};
